"use strict";
(()=>{
if(window.__PROGNOZA_EPIR_SHARED_UI__)return;window.__PROGNOZA_EPIR_SHARED_UI__=true;
const KEY="prognozaepir.theme.preference",LEGACY_KEYS=["prognozaepir-theme","epir-theme"],allowed=new Set(["system","light","dark"]),file=(location.pathname.split("/").pop()||"index.html").replace(/\.html?$/i,"")||"index",page=file==="index"?"index":file;document.documentElement.dataset.epirPage=page;
const EPIR_LAT=52.828611,EPIR_LON=18.330278,EPIR_LOCATION=`Dla Lotniska EPIR · ${EPIR_LAT.toFixed(6)}, ${EPIR_LON.toFixed(6)}`,LOCATION_SUFFIX={index:" · meteogram lotniczy multimodelowy",fog:" · FG / BR / MIFG · UTC",radar:" · radar / satelita / wyładowania","sat-fog":" · EUMETSAT · mgła / niskie chmury",taf:" · generator TAF",arch:" · archiwum depesz","lightning-alerts":" · alarm wyładowań 50 km"};
const media=window.matchMedia?window.matchMedia("(prefers-color-scheme: dark)"):null,read=()=>{try{const c=localStorage.getItem(KEY);if(allowed.has(c))return c;for(const k of LEGACY_KEYS){const v=localStorage.getItem(k);if(v==="light"||v==="dark")return v}}catch(_){}return"system"};let pref=read();
const resolved=()=>pref==="light"||pref==="dark"?pref:(media&&media.matches?"dark":"light"),syncLegacy=t=>{try{for(const k of LEGACY_KEYS)localStorage.setItem(k,t)}catch(_){}},apply=()=>{const t=resolved();document.documentElement.dataset.theme=t;document.documentElement.dataset.themePreference=pref;document.documentElement.style.colorScheme=t;syncLegacy(t);const m=document.querySelector('meta[name="color-scheme"]');if(m)m.setAttribute("content",t);const s=document.getElementById("prognozaepir-theme-select");if(s&&s.value!==pref)s.value=pref;return t},announce=t=>{try{window.dispatchEvent(new CustomEvent("prognozaepir:themechange",{detail:{preference:pref,theme:t}}))}catch(_){}requestAnimationFrame?.(()=>{try{if(typeof window.draw==="function")window.draw()}catch(_){}})},setPref=v=>{pref=allowed.has(v)?v:"system";try{localStorage.setItem(KEY,pref)}catch(_){}announce(apply())};
apply();if(media){const c=()=>{if(pref==="system")announce(apply())};media.addEventListener?media.addEventListener("change",c):media.addListener&&media.addListener(c)}
const NAV=[["index.html","METEOGRAM","index"],["fog.html","EPIR FOG","fog"],["radar.html","RADAR","radar"],["sat-fog.html","MGŁA SAT","sat-fog"],["lightning-alerts.html","WYŁADOWANIA","lightning-alerts"],["taf.html","TAF GENERATOR","taf"],["arch.html","ARCHIWUM","arch"]],canonical=()=>EPIR_LOCATION+(LOCATION_SUFFIX[page]||"");
function syncLocation(){const top=document.querySelector(".top");if(!top)return null;let place=top.querySelector(".place");if(!place){const brand=top.querySelector(".brand");if(!brand)return null;let host=brand.parentElement;if(host===top){host=document.createElement("div");top.insertBefore(host,brand);host.appendChild(brand)}place=document.createElement("div");place.className="place";host.appendChild(place)}const line=canonical();if(place.textContent!==line)place.textContent=line;return place}
function radarGuard(place){if(page!=="radar"||!place||typeof MutationObserver!=="function")return;const lat=document.getElementById("lat"),lon=document.getElementById("lon");let busy=false;const enforce=()=>{if(busy)return;const a=Number(lat?.value),o=Number(lon?.value);if(!Number.isFinite(a)||!Number.isFinite(o)||Math.hypot(a-EPIR_LAT,o-EPIR_LON)>=.001)return;const line=canonical();if(place.textContent!==line){busy=true;place.textContent=line;busy=false}};new MutationObserver(enforce).observe(place,{childList:true,characterData:true,subtree:true});lat?.addEventListener("change",()=>queueMicrotask(enforce));lon?.addEventListener("change",()=>queueMicrotask(enforce));queueMicrotask(enforce)}
function load(src){return new Promise((ok,bad)=>{const s=document.createElement("script");s.src=src;s.async=false;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
function convTitleGuard(){if(page!=="radar"||typeof MutationObserver!=="function")return;const card=document.getElementById("convectionNowcastCard"),h=card?.querySelector("h2");if(!h)return;const fix=()=>{if(h.textContent!=="TCu / Cb · zagrożenie dla EPIR 0–12 h")h.textContent="TCu / Cb · zagrożenie dla EPIR 0–12 h"};fix();new MutationObserver(fix).observe(h,{childList:true,characterData:true,subtree:true})}
async function convection(){if(page!=="index"&&page!=="radar")return;await load("convection-horizon-12h.js?v=20260920-conv12h4");if(page==="radar")convTitleGuard();if(page==="index")await load("meteogram-convection-dots-v2.js?v=20260920-conv12h4")}
function mount(){if(new URLSearchParams(location.search).has("taf-engine"))return;let responsive=document.getElementById("epir-responsive-css");if(!responsive){responsive=document.createElement("link");responsive.id="epir-responsive-css";responsive.rel="stylesheet";responsive.href="responsive.css?v=20260920-r2";document.head.appendChild(responsive)}const place=syncLocation();radarGuard(place);let nav=document.getElementById("epirGlobalNav");if(!nav){nav=document.createElement("nav");nav.id="epirGlobalNav";const root=document.querySelector(".app,.wrap,main")||document.body;root.insertBefore(nav,root.firstChild)}nav.classList.add("epir-global-nav");nav.setAttribute("aria-label","Główna nawigacja PrognozaEPIR");nav.innerHTML=NAV.map(([href,label,id])=>`<a href="${href}"${id===page?' class="active" aria-current="page"':''}>${label}</a>`).join("")+'<label class="epir-theme-slot" for="prognozaepir-theme-select">Motyw <select id="prognozaepir-theme-select" aria-label="Motyw strony"><option value="system">Systemowy</option><option value="light">Jasny</option><option value="dark">Ciemny</option></select></label>';const select=nav.querySelector("#prognozaepir-theme-select");select.value=pref;select.addEventListener("change",()=>setPref(select.value));const old=document.getElementById("themeToggle");if(old){old.setAttribute("aria-hidden","true");old.tabIndex=-1}convection().catch(e=>console.warn("PrognozaEPIR convection",e))}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount,{once:true});else mount();window.PrognozaEPIRTheme=Object.freeze({getPreference:()=>pref,getResolved:resolved,setPreference:setPref});
})();
